/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package ASP.resource.asp.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class AspFollowSetProvider {
	
	public final static ASP.resource.asp.IAspExpectedElement TERMINALS[] = new ASP.resource.asp.IAspExpectedElement[79];
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] FEATURES = new org.eclipse.emf.ecore.EStructuralFeature[8];
	
	public final static ASP.resource.asp.mopp.AspContainedFeature[] LINKS = new ASP.resource.asp.mopp.AspContainedFeature[305];
	
	public final static ASP.resource.asp.mopp.AspContainedFeature[] EMPTY_LINK_ARRAY = new ASP.resource.asp.mopp.AspContainedFeature[0];
	
	public static void initializeTerminals0() {
		TERMINALS[0] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_4_0_0_0);
		TERMINALS[1] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_0);
		TERMINALS[2] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_0);
		TERMINALS[3] = new ASP.resource.asp.mopp.AspExpectedBooleanTerminal(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_0);
		TERMINALS[4] = new ASP.resource.asp.mopp.AspExpectedBooleanTerminal(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_0);
		TERMINALS[5] = new ASP.resource.asp.mopp.AspExpectedBooleanTerminal(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_0);
		TERMINALS[6] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_10_0_0_0);
		TERMINALS[7] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_13_0_0_0);
		TERMINALS[8] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_14_0_0_0);
		TERMINALS[9] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_15_0_0_0);
		TERMINALS[10] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_16_0_0_0);
		TERMINALS[11] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_17_0_0_0);
		TERMINALS[12] = new ASP.resource.asp.mopp.AspExpectedEnumerationTerminal(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_2_0_0_0);
		TERMINALS[13] = new ASP.resource.asp.mopp.AspExpectedEnumerationTerminal(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_3_0_0_0);
		TERMINALS[14] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_11_0_0_0_0_0_0);
		TERMINALS[15] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_12_0_0_0_0_0_0);
		TERMINALS[16] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_12_0_0_1);
		TERMINALS[17] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_2_0_0_2);
		TERMINALS[18] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_2_0_0_3);
		TERMINALS[19] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_3_0_0_2);
		TERMINALS[20] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_3_0_0_3);
		TERMINALS[21] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_4_0_0_1);
		TERMINALS[22] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_4_0_0_2);
		TERMINALS[23] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_4_0_0_4);
		TERMINALS[24] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_4_0_0_5);
		TERMINALS[25] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_1);
		TERMINALS[26] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_2);
		TERMINALS[27] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_4);
		TERMINALS[28] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_5);
		TERMINALS[29] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_7);
		TERMINALS[30] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_5_0_0_8);
		TERMINALS[31] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_1);
		TERMINALS[32] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_2);
		TERMINALS[33] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_4);
		TERMINALS[34] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_5);
		TERMINALS[35] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_7);
		TERMINALS[36] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_8);
		TERMINALS[37] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_10);
		TERMINALS[38] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_6_0_0_11);
		TERMINALS[39] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_1);
		TERMINALS[40] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_2);
		TERMINALS[41] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_4);
		TERMINALS[42] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_5);
		TERMINALS[43] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_7);
		TERMINALS[44] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_7_0_0_8);
		TERMINALS[45] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_1);
		TERMINALS[46] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_2);
		TERMINALS[47] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_4);
		TERMINALS[48] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_5);
		TERMINALS[49] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_7);
		TERMINALS[50] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_8);
		TERMINALS[51] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_10);
		TERMINALS[52] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_8_0_0_11);
		TERMINALS[53] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_1);
		TERMINALS[54] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_2);
		TERMINALS[55] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_4);
		TERMINALS[56] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_5);
		TERMINALS[57] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_7);
		TERMINALS[58] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_8);
		TERMINALS[59] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_10);
		TERMINALS[60] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_11);
		TERMINALS[61] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_13);
		TERMINALS[62] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_9_0_0_14);
		TERMINALS[63] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_10_0_0_2);
		TERMINALS[64] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_10_0_0_4);
		TERMINALS[65] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_10_0_0_5_0_0_0);
		TERMINALS[66] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_10_0_0_7);
		TERMINALS[67] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_10_0_0_5_0_0_2);
		TERMINALS[68] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_11_0_0_3);
		TERMINALS[69] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_11_0_0_6_0_0_0);
		TERMINALS[70] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_11_0_0_8);
		TERMINALS[71] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_12_0_0_4_0_0_0);
		TERMINALS[72] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_12_0_0_6);
		TERMINALS[73] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_13_0_0_1_0_0_1);
		TERMINALS[74] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_15_0_0_2);
		TERMINALS[75] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_16_0_0_2);
		TERMINALS[76] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_16_0_0_4);
		TERMINALS[77] = new ASP.resource.asp.mopp.AspExpectedCsString(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_17_0_0_2);
		TERMINALS[78] = new ASP.resource.asp.mopp.AspExpectedStructuralFeature(ASP.resource.asp.grammar.AspGrammarInformationProvider.ASP_17_0_0_4);
	}
	
	public static void initializeTerminals() {
		initializeTerminals0();
	}
	
	public static void initializeFeatures0() {
		FEATURES[0] = ASP.ASPPackage.eINSTANCE.getRelation().getEStructuralFeature(ASP.ASPPackage.RELATION__PATTERNS);
		FEATURES[1] = ASP.ASPPackage.eINSTANCE.getTransformation().getEStructuralFeature(ASP.ASPPackage.TRANSFORMATION__ELEMENTS);
		FEATURES[2] = ASP.ASPPackage.eINSTANCE.getTransformation().getEStructuralFeature(ASP.ASPPackage.TRANSFORMATION__RELATIONS);
		FEATURES[3] = ASP.ASPPackage.eINSTANCE.getRule().getEStructuralFeature(ASP.ASPPackage.RULE__HEAD);
		FEATURES[4] = ASP.ASPPackage.eINSTANCE.getRule().getEStructuralFeature(ASP.ASPPackage.RULE__EXPRESSIONS);
		FEATURES[5] = ASP.ASPPackage.eINSTANCE.getTransformation().getEStructuralFeature(ASP.ASPPackage.TRANSFORMATION__RULES);
		FEATURES[6] = ASP.ASPPackage.eINSTANCE.getTransformation().getEStructuralFeature(ASP.ASPPackage.TRANSFORMATION__CONSTRAINTS);
		FEATURES[7] = ASP.ASPPackage.eINSTANCE.getConstraint().getEStructuralFeature(ASP.ASPPackage.CONSTRAINT__EXPRESSIONS);
	}
	
	public static void initializeFeatures() {
		initializeFeatures0();
	}
	
	public static void initializeLinks0() {
		LINKS[0] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[1] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[2] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[3] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[4] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[5] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[6] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[7] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[8] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[9] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[10] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[11] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[12] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[13] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[14] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[15] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[16] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[17] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[18] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[19] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[20] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[21] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[22] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[23] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[24] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[25] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[26] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[27] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[28] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[29] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[30] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[31] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[32] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[33] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]);
		LINKS[34] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[35] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[36] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[37] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[38] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]);
		LINKS[39] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[40] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[41] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[42] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[43] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[44] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[45] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[46] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[47] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[48] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[49] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[50] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]);
		LINKS[51] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[52] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[53] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[54] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[55] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[56] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[57] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[58] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[59] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[60] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[61] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[62] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[63] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[64] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[65] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[66] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[67] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[68] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[69] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[70] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[71] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[72] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[73] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[74] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[75] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[76] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[77] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[78] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[79] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[80] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[81] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[82] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[83] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[84] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[85] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[86] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[87] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[88] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[89] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[90] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[91] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[92] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[93] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[94] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[95] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[96] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[97] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[98] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[99] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[100] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[101] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[102] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[103] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[104] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[105] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[106] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[107] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[108] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[109] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[110] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[111] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[112] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[113] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[114] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[115] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[116] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[117] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[118] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[119] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[120] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[121] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[122] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[123] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[124] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[125] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[126] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[127] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[128] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[129] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[130] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[131] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[132] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[133] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[134] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[135] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[136] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[137] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[138] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[139] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[140] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[141] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[142] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[143] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[144] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[145] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[146] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[147] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[148] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[149] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[150] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[151] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[152] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[153] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[154] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[155] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[156] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[157] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[158] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[159] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[160] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[161] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[162] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[163] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[164] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[165] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[166] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[167] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[168] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]);
		LINKS[169] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]);
		LINKS[170] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[4]);
		LINKS[171] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[4]);
		LINKS[172] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[4]);
		LINKS[173] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[4]);
		LINKS[174] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[4]);
		LINKS[175] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[4]);
		LINKS[176] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[4]);
		LINKS[177] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[4]);
		LINKS[178] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[179] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]);
		LINKS[180] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]);
		LINKS[181] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[182] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[183] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[7]);
		LINKS[184] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[7]);
		LINKS[185] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[7]);
		LINKS[186] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[7]);
		LINKS[187] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[7]);
		LINKS[188] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[7]);
		LINKS[189] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[7]);
		LINKS[190] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[7]);
		LINKS[191] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[192] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]);
		LINKS[193] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[194] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[195] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[196] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[197] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[198] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[199] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[200] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[201] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[202] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[203] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[204] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[205] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[206] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[207] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[208] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[209] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[210] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[211] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[212] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[213] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[214] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[215] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[216] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[217] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[218] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[219] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[220] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[221] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[222] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[223] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[224] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[225] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[226] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[227] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[228] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[229] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[230] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[231] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[232] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[233] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[234] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[235] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[236] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[237] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[238] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[239] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[240] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[241] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[242] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[243] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[244] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[245] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[246] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[247] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[248] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[249] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[250] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[251] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[252] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[253] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[254] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[255] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[256] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[257] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[258] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[259] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[260] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[261] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[262] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[263] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[264] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[265] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[266] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[267] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[268] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[269] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[270] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[271] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[272] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[273] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[274] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[275] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[276] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[277] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[278] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[279] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[280] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[281] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[282] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[283] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[284] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[285] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[286] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[287] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[288] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[289] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]);
		LINKS[290] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]);
		LINKS[291] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]);
		LINKS[292] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]);
		LINKS[293] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]);
		LINKS[294] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]);
		LINKS[295] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]);
		LINKS[296] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]);
		LINKS[297] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]);
		LINKS[298] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]);
		LINKS[299] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]);
		LINKS[300] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]);
		LINKS[301] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]);
		LINKS[302] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
		LINKS[303] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]);
		LINKS[304] = new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]);
	}
	
	public static void initializeLinks() {
		initializeLinks0();
	}
	
	public static void wire0() {
		TERMINALS[17].addFollower(TERMINALS[18], EMPTY_LINK_ARRAY);
		TERMINALS[18].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), });
		TERMINALS[19].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[20].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), });
		TERMINALS[0].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[21].addFollower(TERMINALS[22], EMPTY_LINK_ARRAY);
		TERMINALS[22].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[23].addFollower(TERMINALS[24], EMPTY_LINK_ARRAY);
		TERMINALS[24].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[24].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[24].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[1].addFollower(TERMINALS[25], EMPTY_LINK_ARRAY);
		TERMINALS[25].addFollower(TERMINALS[26], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[27], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[28], EMPTY_LINK_ARRAY);
		TERMINALS[28].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[29].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[30].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[30].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[30].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[2].addFollower(TERMINALS[31], EMPTY_LINK_ARRAY);
		TERMINALS[31].addFollower(TERMINALS[32], EMPTY_LINK_ARRAY);
		TERMINALS[32].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[33].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[34].addFollower(TERMINALS[35], EMPTY_LINK_ARRAY);
		TERMINALS[35].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[36].addFollower(TERMINALS[37], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[38], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[38].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[38].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[3].addFollower(TERMINALS[39], EMPTY_LINK_ARRAY);
		TERMINALS[39].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[40].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[41].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[43].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[44].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[44].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[4].addFollower(TERMINALS[45], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[46], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[47], EMPTY_LINK_ARRAY);
		TERMINALS[47].addFollower(TERMINALS[48], EMPTY_LINK_ARRAY);
		TERMINALS[48].addFollower(TERMINALS[49], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[50], EMPTY_LINK_ARRAY);
		TERMINALS[50].addFollower(TERMINALS[51], EMPTY_LINK_ARRAY);
		TERMINALS[51].addFollower(TERMINALS[52], EMPTY_LINK_ARRAY);
		TERMINALS[52].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[52].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[52].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[5].addFollower(TERMINALS[53], EMPTY_LINK_ARRAY);
		TERMINALS[53].addFollower(TERMINALS[54], EMPTY_LINK_ARRAY);
		TERMINALS[54].addFollower(TERMINALS[55], EMPTY_LINK_ARRAY);
		TERMINALS[55].addFollower(TERMINALS[56], EMPTY_LINK_ARRAY);
		TERMINALS[56].addFollower(TERMINALS[57], EMPTY_LINK_ARRAY);
		TERMINALS[57].addFollower(TERMINALS[58], EMPTY_LINK_ARRAY);
		TERMINALS[58].addFollower(TERMINALS[59], EMPTY_LINK_ARRAY);
		TERMINALS[59].addFollower(TERMINALS[60], EMPTY_LINK_ARRAY);
		TERMINALS[60].addFollower(TERMINALS[61], EMPTY_LINK_ARRAY);
		TERMINALS[61].addFollower(TERMINALS[62], EMPTY_LINK_ARRAY);
		TERMINALS[62].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[62].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[62].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[6].addFollower(TERMINALS[63], EMPTY_LINK_ARRAY);
		TERMINALS[63].addFollower(TERMINALS[64], EMPTY_LINK_ARRAY);
		TERMINALS[64].addFollower(TERMINALS[65], EMPTY_LINK_ARRAY);
		TERMINALS[64].addFollower(TERMINALS[66], EMPTY_LINK_ARRAY);
		TERMINALS[65].addFollower(TERMINALS[67], EMPTY_LINK_ARRAY);
		TERMINALS[67].addFollower(TERMINALS[65], EMPTY_LINK_ARRAY);
		TERMINALS[67].addFollower(TERMINALS[66], EMPTY_LINK_ARRAY);
		TERMINALS[66].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[66].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[66].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[14].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]), });
		TERMINALS[68].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[4]), });
		TERMINALS[68].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[4]), });
		TERMINALS[68].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[4]), });
		TERMINALS[68].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[4]), });
		TERMINALS[69].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[4]), });
		TERMINALS[69].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[4]), });
		TERMINALS[69].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[4]), });
		TERMINALS[69].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[4]), });
		TERMINALS[70].addFollower(TERMINALS[14], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]), });
		TERMINALS[70].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[3]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRule(), FEATURES[5]), });
		TERMINALS[70].addFollower(TERMINALS[15], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]), });
		TERMINALS[70].addFollower(TERMINALS[16], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]), });
		TERMINALS[15].addFollower(TERMINALS[16], EMPTY_LINK_ARRAY);
		TERMINALS[16].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[7]), });
		TERMINALS[16].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[7]), });
		TERMINALS[16].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[7]), });
		TERMINALS[16].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[7]), });
		TERMINALS[71].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[7]), });
		TERMINALS[71].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[7]), });
		TERMINALS[71].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[7]), });
		TERMINALS[71].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[7]), });
		TERMINALS[72].addFollower(TERMINALS[15], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]), });
		TERMINALS[72].addFollower(TERMINALS[16], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getConstraint(), FEATURES[6]), });
		TERMINALS[7].addFollower(TERMINALS[73], EMPTY_LINK_ARRAY);
		TERMINALS[7].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[7].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[7].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[73].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[73].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[73].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[8].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[8].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[8].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[8].addFollower(TERMINALS[68], EMPTY_LINK_ARRAY);
		TERMINALS[8].addFollower(TERMINALS[71], EMPTY_LINK_ARRAY);
		TERMINALS[8].addFollower(TERMINALS[72], EMPTY_LINK_ARRAY);
		TERMINALS[9].addFollower(TERMINALS[74], EMPTY_LINK_ARRAY);
		TERMINALS[74].addFollower(TERMINALS[0], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetanode(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[1], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaprop(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[2], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getMetaedge(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[3], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNode(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[4], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getProp(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[5], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEdge(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[6], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNamedFunction(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[7], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLiteral(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[8], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getTerminal(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[9], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNot(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[10], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getEq(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[11], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getNotEq(), FEATURES[1]), });
		TERMINALS[74].addFollower(TERMINALS[12], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getLeftPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[74].addFollower(TERMINALS[13], new ASP.resource.asp.mopp.AspContainedFeature[] {new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRightPattern(), FEATURES[0]), new ASP.resource.asp.mopp.AspContainedFeature(ASP.ASPPackage.eINSTANCE.getRelation(), FEATURES[2]), });
		TERMINALS[74].addFollower(TERMINALS[69], EMPTY_LINK_ARRAY);
		TERMINALS[74].addFollower(TERMINALS[70], EMPTY_LINK_ARRAY);
		TERMINALS[74].addFollower(TERMINALS[71], EMPTY_LINK_ARRAY);
		TERMINALS[74].addFollower(TERMINALS[72], EMPTY_LINK_ARRAY);
	}
	
	public static void wire() {
		wire0();
	}
	
	static {
		// initialize the arrays
		initializeTerminals();
		initializeFeatures();
		initializeLinks();
		// wire the terminals
		wire();
	}
}
