/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package JTL.resource.jtl.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class JtlFollowSetProvider {
	
	public final static JTL.resource.jtl.IJtlExpectedElement TERMINALS[] = new JTL.resource.jtl.IJtlExpectedElement[53];
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] FEATURES = new org.eclipse.emf.ecore.EStructuralFeature[13];
	
	public final static JTL.resource.jtl.mopp.JtlContainedFeature[] LINKS = new JTL.resource.jtl.mopp.JtlContainedFeature[249];
	
	public final static JTL.resource.jtl.mopp.JtlContainedFeature[] EMPTY_LINK_ARRAY = new JTL.resource.jtl.mopp.JtlContainedFeature[0];
	
	public static void initializeTerminals0() {
		TERMINALS[0] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_0);
		TERMINALS[1] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_1);
		TERMINALS[2] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_3);
		TERMINALS[3] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_1_0_0_0);
		TERMINALS[4] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_5);
		TERMINALS[5] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_4_0_0_1_0_0_0);
		TERMINALS[6] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_7);
		TERMINALS[7] = new JTL.resource.jtl.mopp.JtlExpectedBooleanTerminal(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_2_0_0_0);
		TERMINALS[8] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_2_0_0_1);
		TERMINALS[9] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_0_0_0_10);
		TERMINALS[10] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_1_0_0_1);
		TERMINALS[11] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_1_0_0_2);
		TERMINALS[12] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_2_0_0_2);
		TERMINALS[13] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_2_0_0_4);
		TERMINALS[14] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_14_0_0_0);
		TERMINALS[15] = new JTL.resource.jtl.mopp.JtlExpectedBooleanTerminal(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_3_0_0_0);
		TERMINALS[16] = new JTL.resource.jtl.mopp.JtlExpectedBooleanTerminal(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_3_0_0_1);
		TERMINALS[17] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_3_0_0_2);
		TERMINALS[18] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_5_0_0_0);
		TERMINALS[19] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_6_0_0_0);
		TERMINALS[20] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_2_0_0_10);
		TERMINALS[21] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_3_0_0_3);
		TERMINALS[22] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_0);
		TERMINALS[23] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_4_0_0_2);
		TERMINALS[24] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_9_0_0_0);
		TERMINALS[25] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_10_0_0_0);
		TERMINALS[26] = new JTL.resource.jtl.mopp.JtlExpectedBooleanTerminal(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_11_0_0_0);
		TERMINALS[27] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_12_0_0_0);
		TERMINALS[28] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_13_0_0_0);
		TERMINALS[29] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_4_0_0_4);
		TERMINALS[30] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_4_0_0_3_0_0_2_0_0_0);
		TERMINALS[31] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_5_0_0_2);
		TERMINALS[32] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_5_0_0_5);
		TERMINALS[33] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_5_0_0_3_0_0_2);
		TERMINALS[34] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_6_0_0_2);
		TERMINALS[35] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_6_0_0_5);
		TERMINALS[36] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_6_0_0_3_0_0_2);
		TERMINALS[37] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_2);
		TERMINALS[38] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_3_0_0_1);
		TERMINALS[39] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_4_0_0_0);
		TERMINALS[40] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_5_0_0_1);
		TERMINALS[41] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_5_0_0_2_0_0_2_0_0_0);
		TERMINALS[42] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_5_0_0_4);
		TERMINALS[43] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_10_0_0_2_0_0_1_0_0_0);
		TERMINALS[44] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_10_0_0_3);
		TERMINALS[45] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_8_0_0_4_0_0_1);
		TERMINALS[46] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_9_0_0_2);
		TERMINALS[47] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_10_0_0_1);
		TERMINALS[48] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_13_0_0_1);
		TERMINALS[49] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_13_0_0_2);
		TERMINALS[50] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_14_0_0_1_0_0_1);
		TERMINALS[51] = new JTL.resource.jtl.mopp.JtlExpectedCsString(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_14_0_0_2);
		TERMINALS[52] = new JTL.resource.jtl.mopp.JtlExpectedStructuralFeature(JTL.resource.jtl.grammar.JtlGrammarInformationProvider.JTL_14_0_0_1_0_0_3);
	}
	
	public static void initializeTerminals() {
		initializeTerminals0();
	}
	
	public static void initializeFeatures0() {
		FEATURES[0] = JTL.JTL.JTLPackage.eINSTANCE.getTransformation().getEStructuralFeature(JTL.JTL.JTLPackage.TRANSFORMATION__MODEL_PARAMETER);
		FEATURES[1] = JTL.JTL.JTLPackage.eINSTANCE.getTransformation().getEStructuralFeature(JTL.JTL.JTLPackage.TRANSFORMATION__RELATION);
		FEATURES[2] = JTL.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTL.JTL.JTLPackage.RELATION__VARIABLE);
		FEATURES[3] = JTL.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTL.JTL.JTLPackage.RELATION__DOMAIN);
		FEATURES[4] = JTL.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTL.JTL.JTLPackage.RELATION__WHEN);
		FEATURES[5] = JTL.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTL.JTL.JTLPackage.RELATION__WHERE);
		FEATURES[6] = JTL.JTL.JTLPackage.eINSTANCE.getPattern().getEStructuralFeature(JTL.JTL.JTLPackage.PATTERN__TEMPLATE_EXPRESSION);
		FEATURES[7] = JTL.JTL.JTLPackage.eINSTANCE.getDomain().getEStructuralFeature(JTL.JTL.JTLPackage.DOMAIN__PATTERN);
		FEATURES[8] = JTL.JTL.JTLPackage.eINSTANCE.getPredicate().getEStructuralFeature(JTL.JTL.JTLPackage.PREDICATE__CONDITION_EXPRESSION);
		FEATURES[9] = JTL.JTL.JTLPackage.eINSTANCE.getPattern().getEStructuralFeature(JTL.JTL.JTLPackage.PATTERN__PREDICATE);
		FEATURES[10] = JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp().getEStructuralFeature(JTL.imperativeocl.ImperativeoclPackage.ASSIGN_EXP__VALUE);
		FEATURES[11] = JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp().getEStructuralFeature(JTL.template.TemplatePackage.OBJECT_TEMPLATE_EXP__INSIDE);
		FEATURES[12] = JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp().getEStructuralFeature(JTL.essentialocl.EssentialoclPackage.OPERATION_CALL_EXP__ARGUMENT);
	}
	
	public static void initializeFeatures() {
		initializeFeatures0();
	}
	
	public static void initializeLinks0() {
		LINKS[0] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]);
		LINKS[1] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]);
		LINKS[2] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[3] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[4] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[5] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[6] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[7] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[8] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[9] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[10] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[11] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[12] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[13] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[14] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[15] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[16] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[17] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[18] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[19] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[20] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[21] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[22] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[23] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[24] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[25] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[26] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[27] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[28] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[29] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[30] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[31] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[32] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[33] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[34] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[35] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[36] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[37] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[38] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[39] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[40] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[6]);
		LINKS[41] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[7]);
		LINKS[42] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[7]);
		LINKS[43] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[7]);
		LINKS[44] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[45] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[46] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[47] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[48] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[49] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[50] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[51] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[52] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[53] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[54] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[55] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[56] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[57] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[58] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[59] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[60] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[61] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[62] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[63] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[64] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[65] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[66] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[67] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[68] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[69] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[70] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[71] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[72] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[73] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[74] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[75] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[76] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[77] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[78] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[79] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[80] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[81] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[82] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[83] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[84] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[85] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[86] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[87] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[88] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[89] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[90] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[91] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[92] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[93] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[94] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[95] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[96] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[97] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[98] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[99] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[100] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[101] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[102] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[103] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[104] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[105] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[106] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[107] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[108] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[109] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[110] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[111] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[112] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[113] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[114] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
		LINKS[115] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[116] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[117] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[118] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[119] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[120] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[121] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[122] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[123] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[124] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[125] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[126] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[127] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[128] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[129] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[130] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[131] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[132] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[133] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[134] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[135] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[136] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[137] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[138] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[139] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]);
		LINKS[140] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[141] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]);
		LINKS[142] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[143] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]);
		LINKS[144] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[145] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]);
		LINKS[146] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[147] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]);
		LINKS[148] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[149] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]);
		LINKS[150] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]);
		LINKS[151] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[152] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[153] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[154] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[155] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[156] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[157] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[158] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[159] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[160] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[161] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[162] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[163] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[164] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[165] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[166] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[167] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[168] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[169] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[170] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[171] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[172] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[173] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[174] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[175] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[176] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[177] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[178] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[179] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[180] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[181] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]);
		LINKS[182] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]);
		LINKS[183] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[184] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[185] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[186] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[187] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[188] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[189] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[190] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[191] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[192] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[193] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[194] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[195] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[196] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[197] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[198] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[199] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[200] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[201] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[202] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[203] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[204] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[205] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[206] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[207] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]);
		LINKS[208] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]);
		LINKS[209] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]);
		LINKS[210] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]);
		LINKS[211] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]);
		LINKS[212] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]);
		LINKS[213] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]);
		LINKS[214] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]);
		LINKS[215] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]);
		LINKS[216] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]);
		LINKS[217] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]);
		LINKS[218] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]);
		LINKS[219] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[220] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[221] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[222] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[223] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[224] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[225] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[226] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[227] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[228] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[229] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[230] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[231] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[232] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[233] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[234] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[235] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[236] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[237] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[238] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[239] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[240] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[241] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[242] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[243] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[244] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[245] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[246] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[247] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]);
		LINKS[248] = new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]);
	}
	
	public static void initializeLinks() {
		initializeLinks0();
	}
	
	public static void wire0() {
		TERMINALS[0].addFollower(TERMINALS[1], EMPTY_LINK_ARRAY);
		TERMINALS[1].addFollower(TERMINALS[2], EMPTY_LINK_ARRAY);
		TERMINALS[2].addFollower(TERMINALS[3], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]), });
		TERMINALS[2].addFollower(TERMINALS[4], EMPTY_LINK_ARRAY);
		TERMINALS[5].addFollower(TERMINALS[3], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]), });
		TERMINALS[4].addFollower(TERMINALS[6], EMPTY_LINK_ARRAY);
		TERMINALS[6].addFollower(TERMINALS[7], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[6].addFollower(TERMINALS[8], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[3].addFollower(TERMINALS[10], EMPTY_LINK_ARRAY);
		TERMINALS[10].addFollower(TERMINALS[11], EMPTY_LINK_ARRAY);
		TERMINALS[11].addFollower(TERMINALS[5], EMPTY_LINK_ARRAY);
		TERMINALS[11].addFollower(TERMINALS[4], EMPTY_LINK_ARRAY);
		TERMINALS[7].addFollower(TERMINALS[8], EMPTY_LINK_ARRAY);
		TERMINALS[8].addFollower(TERMINALS[12], EMPTY_LINK_ARRAY);
		TERMINALS[12].addFollower(TERMINALS[13], EMPTY_LINK_ARRAY);
		TERMINALS[13].addFollower(TERMINALS[14], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]), });
		TERMINALS[13].addFollower(TERMINALS[15], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[13].addFollower(TERMINALS[16], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[13].addFollower(TERMINALS[17], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[13].addFollower(TERMINALS[18], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]), });
		TERMINALS[13].addFollower(TERMINALS[19], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]), });
		TERMINALS[13].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[20].addFollower(TERMINALS[7], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[20].addFollower(TERMINALS[8], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[20].addFollower(TERMINALS[9], EMPTY_LINK_ARRAY);
		TERMINALS[15].addFollower(TERMINALS[16], EMPTY_LINK_ARRAY);
		TERMINALS[15].addFollower(TERMINALS[17], EMPTY_LINK_ARRAY);
		TERMINALS[16].addFollower(TERMINALS[17], EMPTY_LINK_ARRAY);
		TERMINALS[17].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[21].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[6]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[7]), });
		TERMINALS[21].addFollower(TERMINALS[18], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[7]), });
		TERMINALS[21].addFollower(TERMINALS[19], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[7]), });
		TERMINALS[23].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[23].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[23].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[23].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[23].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[23].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[23].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[30].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[30].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[30].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[30].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[30].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[30].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[29].addFollower(TERMINALS[15], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[29].addFollower(TERMINALS[16], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[29].addFollower(TERMINALS[17], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[29].addFollower(TERMINALS[18], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]), });
		TERMINALS[29].addFollower(TERMINALS[19], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]), });
		TERMINALS[29].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[18].addFollower(TERMINALS[31], EMPTY_LINK_ARRAY);
		TERMINALS[31].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[31].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[31].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[31].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[31].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[31].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[31].addFollower(TERMINALS[32], EMPTY_LINK_ARRAY);
		TERMINALS[33].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[33].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[33].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[33].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[33].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[33].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[33].addFollower(TERMINALS[32], EMPTY_LINK_ARRAY);
		TERMINALS[32].addFollower(TERMINALS[19], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]), });
		TERMINALS[32].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[19].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[34].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[34].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[34].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[34].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[34].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[34].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[34].addFollower(TERMINALS[35], EMPTY_LINK_ARRAY);
		TERMINALS[36].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[36].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[36].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[36].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[36].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[36].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[8]), new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[9]), });
		TERMINALS[36].addFollower(TERMINALS[35], EMPTY_LINK_ARRAY);
		TERMINALS[35].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[22].addFollower(TERMINALS[37], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[38], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[39], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[39], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[39].addFollower(TERMINALS[45], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[40].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]), });
		TERMINALS[40].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[41].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]), });
		TERMINALS[42].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[24].addFollower(TERMINALS[46], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[25].addFollower(TERMINALS[47], EMPTY_LINK_ARRAY);
		TERMINALS[47].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[43].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]), });
		TERMINALS[44].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[28].addFollower(TERMINALS[48], EMPTY_LINK_ARRAY);
		TERMINALS[48].addFollower(TERMINALS[49], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[36], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[22], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[24], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[25], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[26], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[27], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[28], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[14].addFollower(TERMINALS[50], EMPTY_LINK_ARRAY);
		TERMINALS[14].addFollower(TERMINALS[51], EMPTY_LINK_ARRAY);
		TERMINALS[50].addFollower(TERMINALS[52], EMPTY_LINK_ARRAY);
		TERMINALS[52].addFollower(TERMINALS[51], EMPTY_LINK_ARRAY);
		TERMINALS[51].addFollower(TERMINALS[14], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]), });
		TERMINALS[51].addFollower(TERMINALS[15], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[51].addFollower(TERMINALS[16], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[51].addFollower(TERMINALS[17], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[51].addFollower(TERMINALS[18], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhen(), FEATURES[4]), });
		TERMINALS[51].addFollower(TERMINALS[19], new JTL.resource.jtl.mopp.JtlContainedFeature[] {new JTL.resource.jtl.mopp.JtlContainedFeature(JTL.JTL.JTLPackage.eINSTANCE.getWhere(), FEATURES[5]), });
		TERMINALS[51].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
	}
	
	public static void wire() {
		wire0();
	}
	
	static {
		// initialize the arrays
		initializeTerminals();
		initializeFeatures();
		initializeLinks();
		// wire the terminals
		wire();
	}
}
